# Site setings
name: 'Horace'
description: 'Horace is a simple Jekyll theme for writers and bloggers. Explore it yourself.'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://blog.chrishou.se
disqus: 'blog-chrishou-se'
mailchimp_url: 
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: UA-133347879-1


# Author
author:
  name: 'Christopher House'
  image: 'authorimage.jpg'
  greetings: 'Hi there!'
  description: "My name is Chris House, I'm a Cloud Solution Architect based in Saint Paul, Minnesota."
  bio: 'Chris House is a Cloud Solution Architect for Microsoft, based in Saint Paul, Minnesota.  Over the span of his career, Chris has worked extensively in .Net application development and architecture, integration, and cloud architecture.'

# Contact form setings
email: youremail@email.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: '13daysaweek'
facebook: 
github: '13daysaweek'
codepen: 
dribbble: 
medium: 
instagram: 
pinterest: 
linkedin: 'christopher-house-8b2a577'
producthunt: 

# Navigation
navigation:
  - text: About
    url: /about/
##  - text: Style Guide
##    url: /style-guide/
##  - text: Contact Me
##    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
